/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package grafica;

import datos.IngresoMoto;
import static datos.SalidaMoto.calcularPrecio;
import java.awt.Color;
import java.awt.Component;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.Scanner;
import java.util.Timer;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author NATALYVARGAS
 */
public class Ventana extends javax.swing.JFrame {
    DefaultTableModel modelo=new DefaultTableModel();
    Calendar FechaHora=new GregorianCalendar();
    /**
     * Creates new form Ventana
     */
    public Ventana() {
        initComponents();
        this.modelo.addColumn("Identificacion");
        this.modelo.addColumn("Placa");
        this.modelo.addColumn("Fecha Y Hora");
        Tabla.setModel(modelo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btg1 = new javax.swing.ButtonGroup();
        opIngreso = new javax.swing.JRadioButton();
        opSalida = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        cjIdentificacion = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        cjPlaca = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        cjFecha = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        cjHora = new javax.swing.JTextField();
        btGuardar = new javax.swing.JButton();
        btNuevo = new javax.swing.JButton();
        Eliminar = new javax.swing.JButton();
        btSalir = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tabla = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        btg1.add(opIngreso);
        opIngreso.setText("Ingreso");
        opIngreso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opIngresoActionPerformed(evt);
            }
        });
        opIngreso.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                opIngresoKeyReleased(evt);
            }
        });
        getContentPane().add(opIngreso);
        opIngreso.setBounds(100, 90, 120, 25);

        btg1.add(opSalida);
        opSalida.setText("Salida");
        opSalida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opSalidaActionPerformed(evt);
            }
        });
        getContentPane().add(opSalida);
        opSalida.setBounds(400, 90, 120, 25);

        jLabel1.setText("Identificación");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(70, 140, 90, 20);

        cjIdentificacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cjIdentificacionActionPerformed(evt);
            }
        });
        getContentPane().add(cjIdentificacion);
        cjIdentificacion.setBounds(50, 180, 140, 20);

        jLabel2.setText("Fecha");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(420, 140, 60, 20);

        cjPlaca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cjPlacaActionPerformed(evt);
            }
        });
        getContentPane().add(cjPlaca);
        cjPlaca.setBounds(380, 180, 130, 20);

        jLabel3.setText("Placa");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(260, 140, 60, 20);

        cjFecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cjFechaActionPerformed(evt);
            }
        });
        getContentPane().add(cjFecha);
        cjFecha.setBounds(220, 180, 130, 20);

        jLabel4.setText("Hora");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(580, 140, 50, 16);

        cjHora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cjHoraActionPerformed(evt);
            }
        });
        getContentPane().add(cjHora);
        cjHora.setBounds(540, 180, 120, 22);

        btGuardar.setText("Guardar");
        btGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btGuardarActionPerformed(evt);
            }
        });
        getContentPane().add(btGuardar);
        btGuardar.setBounds(60, 230, 90, 25);

        btNuevo.setText("Nuevo");
        btNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btNuevoActionPerformed(evt);
            }
        });
        getContentPane().add(btNuevo);
        btNuevo.setBounds(200, 230, 100, 25);

        Eliminar.setText("Eliminar Moto");
        Eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarActionPerformed(evt);
            }
        });
        getContentPane().add(Eliminar);
        Eliminar.setBounds(340, 230, 150, 25);

        btSalir.setText("Salir");
        btSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSalirActionPerformed(evt);
            }
        });
        getContentPane().add(btSalir);
        btSalir.setBounds(540, 230, 80, 25);

        jLabel5.setText("PARQUEADERO DE MOTOS ");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(210, 16, 220, 40);

        Tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(Tabla);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(90, 270, 470, 250);

        setSize(new java.awt.Dimension(709, 549));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cjIdentificacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cjIdentificacionActionPerformed
       if(opIngreso.isSelected());
    }//GEN-LAST:event_cjIdentificacionActionPerformed

    private void btGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btGuardarActionPerformed
        //JOptionPane.showMessageDialog(this, "Su vehículo se registró");
        if(opIngreso.isSelected()){
        String Dato[]=new String[4];
        Dato[0]=cjIdentificacion.getText();
        Dato[1]=cjPlaca.getText();
        Dato[2] = cjFecha.getText();
        Dato[3]=cjHora.getText();
        modelo.addRow(Dato);
          this.registrarMoto();  
        }else {
        String Dato[]=new String[4];
        if(opSalida.isSelected())
        Dato[1]=cjPlaca.getText();
        Dato[2] = cjFecha.getText();
        this.salidaMoto();}
         
        //this.registrarVehiculo();
    }//GEN-LAST:event_btGuardarActionPerformed

    private void btSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btSalirActionPerformed

    private void opSalidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opSalidaActionPerformed

    }//GEN-LAST:event_opSalidaActionPerformed

    private void opIngresoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_opIngresoKeyReleased
        if(opIngreso.isSelected()){
            cjIdentificacion.setEnabled(true);
        }else if (opIngreso.isSelected()){
            cjIdentificacion.setEnabled(false);
        }
    }//GEN-LAST:event_opIngresoKeyReleased

    private void opIngresoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opIngresoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_opIngresoActionPerformed

    private void cjPlacaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cjPlacaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cjPlacaActionPerformed

    private void btNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btNuevoActionPerformed
      cjIdentificacion.setText(" ");
      cjPlaca.setText(" ");
      cjIdentificacion.requestFocus();

    }//GEN-LAST:event_btNuevoActionPerformed

    private void EliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarActionPerformed
     int FilaSelec = Tabla.getSelectedRow();
     if(FilaSelec>=0){
         modelo.removeRow(FilaSelec);
     }
     else{
         JOptionPane.showMessageDialog(this, "Fila no seleccionada");
     }
    }//GEN-LAST:event_EliminarActionPerformed

    private void cjHoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cjHoraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cjHoraActionPerformed

    private void cjFechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cjFechaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cjFechaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana().setVisible(true);
            }
        });
    }
    public void registrarMoto(){
        String placa = cjPlaca.getText();
        //Date fecha = cjFecha.getDate();
        //Timer hora = cjHora.getTimer();
        String identificacion = cjIdentificacion.getText();
        JOptionPane.showMessageDialog(this, "Su moto fue registrado exitosamente");
    }
    public void salidaMotoo(){
        String placa = cjPlaca.getText();
       
         int numMinutos=0;
        double precioTotal=0;
        Scanner sc=new Scanner (System.in);
       System.out.println("Cantidad de minutos: ");
       numMinutos=sc.nextInt();
       precioTotal=calcularPrecio(numMinutos);
       System.out.println("Total a pagar "+precioTotal);
        JOptionPane.showMessageDialog(this, "Puede retirar su moto");
    }
    
    public void habilitar(){
        if(opIngreso.isSelected()){
        cjIdentificacion.setEnabled(true);
        cjPlaca.setEnabled(true);
        
        }else if (opSalida.isSelected()){
            cjIdentificacion.setEnabled(false);
        Calendar fecha_actual=new GregorianCalendar();
        }
    }



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Eliminar;
    private javax.swing.JTable Tabla;
    private javax.swing.JButton btGuardar;
    private javax.swing.JButton btNuevo;
    private javax.swing.JButton btSalir;
    private javax.swing.ButtonGroup btg1;
    private javax.swing.JTextField cjFecha;
    private javax.swing.JTextField cjHora;
    private javax.swing.JTextField cjIdentificacion;
    private javax.swing.JTextField cjPlaca;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton opIngreso;
    private javax.swing.JRadioButton opSalida;
    // End of variables declaration//GEN-END:variables

    private void salidaMoto() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    
}
